-- MySQL Script generated by MySQL Workbench
-- Mon Jul  6 20:33:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Insituto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Insituto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Insituto` DEFAULT CHARACTER SET utf8 ;
USE `Insituto` ;

-- -----------------------------------------------------
-- Table `Insituto`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`alumno` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`periodo` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `inicio` DATE NOT NULL,
  `final` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `id_periodo` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `cupos` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_curso`),
  CONSTRAINT `fk_curso_periodo1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `Insituto`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`profesor` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `id_profesor` INT NOT NULL,
  `id_curso` INT NOT NULL,
  `cupos` INT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Insituto`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_profesor1`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `Insituto`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`calificaiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`calificaiones` (
  `id_calificaiones` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_alumno` INT NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`id_calificaiones`),
  CONSTRAINT `fk_calificaiones_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Insituto`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaiones_alumno1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `Insituto`.`alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`tematica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`tematica` (
  `id_tematica` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `silabo` TEXT NOT NULL,
  PRIMARY KEY (`id_tematica`),
  CONSTRAINT `fk_tematica_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Insituto`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`unidad` (
  `id_unidad` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`id_unidad`),
  CONSTRAINT `fk_unidad_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Insituto`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`banco_preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`banco_preguntas` (
  `id_banco_preguntas` INT NOT NULL,
  `id_unidad` INT NOT NULL,
  PRIMARY KEY (`id_banco_preguntas`),
  CONSTRAINT `fk_banco_preguntas_unidad1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `Insituto`.`unidad` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`pregunta` (
  `id_pregunta` INT NOT NULL AUTO_INCREMENT,
  `id_banco_preguntas` INT NOT NULL,
  `planteamiento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_pregunta`),
  CONSTRAINT `fk_pregunta_banco_preguntas1`
    FOREIGN KEY (`id_banco_preguntas`)
    REFERENCES `Insituto`.`banco_preguntas` (`id_banco_preguntas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`Desarrollo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`Desarrollo` (
  `id_Desarrollo` INT NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT NOT NULL,
  `reglones` INT NOT NULL,
  PRIMARY KEY (`id_Desarrollo`),
  CONSTRAINT `fk_Desarrollo_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `Insituto`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`concreta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`concreta` (
  `id_concreta` INT NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT NOT NULL,
  `respuesta` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_concreta`),
  CONSTRAINT `fk_concreta_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `Insituto`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`alternativa` (
  `id_alternativa` INT NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT NOT NULL,
  `Resp` VARCHAR(15) NOT NULL,
  `A` VARCHAR(15) NOT NULL,
  `B` VARCHAR(15) NOT NULL,
  `C` VARCHAR(15) NOT NULL,
  `D` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_alternativa`),
  CONSTRAINT `fk_alternativa_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `Insituto`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`true_false`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`true_false` (
  `id_true_false` INT NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT NOT NULL,
  `correcto` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_true_false`),
  CONSTRAINT `fk_true_false_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `Insituto`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`emparejamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`emparejamiento` (
  `id_emparejamiento` INT NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT NOT NULL,
  `pareja` VARCHAR(70) NOT NULL,
  `emparejado` VARCHAR(70) NULL,
  PRIMARY KEY (`id_emparejamiento`),
  CONSTRAINT `fk_emparejamiento_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `Insituto`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`examen` (
  `id_examen` INT NOT NULL AUTO_INCREMENT,
  `id_grupo` INT NOT NULL,
  `tipo` VARCHAR(11) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `duracion` INT NOT NULL,
  PRIMARY KEY (`id_examen`),
  CONSTRAINT `fk_examen_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `Insituto`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`matricula` (
  `id_alumno` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  CONSTRAINT `fk_matricula_persona1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `Insituto`.`alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `Insituto`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`pertenece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`pertenece` (
  `id_pregunta` INT NOT NULL,
  `id_examen` INT NOT NULL,
  CONSTRAINT `fk_pertenece_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `Insituto`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_examen1`
    FOREIGN KEY (`id_examen`)
    REFERENCES `Insituto`.`examen` (`id_examen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`caracteristica` (
  `id_caracteristica` INT NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT NOT NULL,
  `duracion` INT NOT NULL,
  `puntuacion` INT NOT NULL,
  PRIMARY KEY (`id_caracteristica`),
  CONSTRAINT `fk_puntaje_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `Insituto`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Insituto`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insituto`.`director` (
  `id_director` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_director`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
