-- MySQL Script generated by MySQL Workbench
-- Sat Apr 11 14:45:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sistema_GCE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sistema_GCE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sistema_GCE` DEFAULT CHARACTER SET utf8 ;
USE `Sistema_GCE` ;

-- -----------------------------------------------------
-- Table `Sistema_GCE`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`periodo` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `inicio` DATE NOT NULL,
  `final` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `id_periodo` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `cupos` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_curso`),
  CONSTRAINT `fk_curso_periodo1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `Sistema_GCE`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_profesor` INT NOT NULL,
  `cupos` INT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Sistema_GCE`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_persona1`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `Sistema_GCE`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`calificaiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`calificaiones` (
  `id_calificaiones` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `id_curso` INT NOT NULL,
  `nota` INT NULL,
  PRIMARY KEY (`id_calificaiones`),
  CONSTRAINT `fk_calificaiones_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Sistema_GCE`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaiones_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `Sistema_GCE`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`tematica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`tematica` (
  `id_tematica` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `silabo` TEXT NOT NULL,
  PRIMARY KEY (`id_tematica`),
  CONSTRAINT `fk_tematica_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Sistema_GCE`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`unidad` (
  `id_unidad` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`id_unidad`),
  CONSTRAINT `fk_unidad_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Sistema_GCE`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`banco_preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`banco_preguntas` (
  `id_banco_preguntas` INT NOT NULL,
  `id_unidad` INT NOT NULL,
  PRIMARY KEY (`id_banco_preguntas`),
  CONSTRAINT `fk_banco_preguntas_unidad1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `Sistema_GCE`.`unidad` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`pregunta` (
  `id_pregunta` INT NOT NULL,
  `id_banco_preguntas` INT NOT NULL,
  `planteamiento` VARCHAR(100) NOT NULL,
  `puntaje` INT NOT NULL,
  `duracion` INT NOT NULL,
  PRIMARY KEY (`id_pregunta`),
  CONSTRAINT `fk_pregunta_banco_preguntas1`
    FOREIGN KEY (`id_banco_preguntas`)
    REFERENCES `Sistema_GCE`.`banco_preguntas` (`id_banco_preguntas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`Desarrollo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`Desarrollo` (
  `id_Desarrollo` INT NOT NULL,
  `reglones` INT NOT NULL,
  `respuesta` TEXT NOT NULL,
  `envio` TEXT NULL,
  `pregunta_id_pregunta` INT NOT NULL,
  PRIMARY KEY (`id_Desarrollo`),
  CONSTRAINT `fk_Desarrollo_pregunta1`
    FOREIGN KEY (`pregunta_id_pregunta`)
    REFERENCES `Sistema_GCE`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`concreta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`concreta` (
  `id_concreta` INT NOT NULL,
  `respuesta` VARCHAR(80) NOT NULL,
  `envio` VARCHAR(80) NULL,
  `pregunta_id_pregunta` INT NOT NULL,
  PRIMARY KEY (`id_concreta`),
  CONSTRAINT `fk_concreta_pregunta1`
    FOREIGN KEY (`pregunta_id_pregunta`)
    REFERENCES `Sistema_GCE`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`alternativa` (
  `id_alternativa` INT NOT NULL,
  `premisa` TEXT NOT NULL,
  `correcta` TINYINT NOT NULL,
  `marcada` TINYTEXT NULL,
  `pregunta_id_pregunta` INT NOT NULL,
  PRIMARY KEY (`id_alternativa`),
  CONSTRAINT `fk_alternativa_pregunta1`
    FOREIGN KEY (`pregunta_id_pregunta`)
    REFERENCES `Sistema_GCE`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`true_false`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`true_false` (
  `id_true_false` INT NOT NULL,
  `premisa` VARCHAR(100) NOT NULL,
  `correcto` VARCHAR(1) NOT NULL,
  `respuesta` VARCHAR(1) NULL,
  `pregunta_id_pregunta` INT NOT NULL,
  PRIMARY KEY (`id_true_false`),
  CONSTRAINT `fk_true_false_pregunta1`
    FOREIGN KEY (`pregunta_id_pregunta`)
    REFERENCES `Sistema_GCE`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`emparejamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`emparejamiento` (
  `id_emparejamiento` INT NOT NULL,
  `premisa` VARCHAR(70) NOT NULL,
  `pareja` VARCHAR(70) NOT NULL,
  `emparejado` VARCHAR(70) NULL,
  `pregunta_id_pregunta` INT NOT NULL,
  PRIMARY KEY (`id_emparejamiento`),
  CONSTRAINT `fk_emparejamiento_pregunta1`
    FOREIGN KEY (`pregunta_id_pregunta`)
    REFERENCES `Sistema_GCE`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`examen` (
  `id_examen` INT NOT NULL,
  `tipo` VARCHAR(11) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `duracion` INT NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_examen`),
  CONSTRAINT `fk_examen_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `Sistema_GCE`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`credencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`credencial` (
  `id_credencial` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `dni` VARCHAR(8) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_credencial`),
  CONSTRAINT `fk_credencial_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `Sistema_GCE`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`roles` (
  `id_roles` INT NOT NULL,
  `id_credencial` INT NOT NULL,
  `nombre` VARCHAR(8) NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_roles`),
  CONSTRAINT `fk_roles_credencial1`
    FOREIGN KEY (`id_credencial`)
    REFERENCES `Sistema_GCE`.`credencial` (`id_credencial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`matricula` (
  `id_persona` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  CONSTRAINT `fk_matricula_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `Sistema_GCE`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `Sistema_GCE`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_GCE`.`pertenece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_GCE`.`pertenece` (
  `id_pregunta` INT NOT NULL,
  `id_examen` INT NOT NULL,
  CONSTRAINT `fk_pertenece_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `Sistema_GCE`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_examen1`
    FOREIGN KEY (`id_examen`)
    REFERENCES `Sistema_GCE`.`examen` (`id_examen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
